app_ventas_ds504_cf/Models/ErrorViewModel.cs
namespace app_ventas_ds504_cf.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

app_ventas_ds504_cf/Models/Marca.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace web_ventas_ds504_cf.Models
{
    [Table("tb_marca")]
    public class Marca
    {
        [Key]
        [Required(ErrorMessage = "Ingrese el código de la marca")]
        [StringLength(5)]
        [Display(Name = "Código de Marca")]
        public string? codigo_marca { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre de la marca")]
        [StringLength(30)]
        [Display(Name = "Marca")]
        public string? marca { get; set; }
    }

}

app_ventas_ds504_cf/Models/Personal.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoDS504_cf.Models
{
    [Table("tb_personal")]
    public class Personal
    {
        [Key]
        [Required(ErrorMessage = "Ingrese el número de DNI.")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "El número de DNI debe tener 8 dígitos.")]
        [Display(Name = "Número de DNI")]
        public string? dni { get; set; }

        [Required(ErrorMessage = "Ingrese el apellido paterno.")]
        [StringLength(25)]
        [Display(Name = "Apellido Paterno")]
        public string? ap_paterno { get; set; }

        [Required(ErrorMessage = "Ingrese el apellido materno.")]
        [StringLength(25)]
        [Display(Name = "Apellido Materno")]
        public string? ap_materno { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre.")]
        [StringLength(25)]
        [Display(Name = "Nombre")]
        public string? nombre { get; set; }

        [Display(Name = "Género")]
        public string? genero { get; set; }

        [Required(ErrorMessage = "Ingrese una fecha de nacimiento")]
        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public DateTime fecha_nacimiento { get; set; }

        [Required(ErrorMessage = "Ingrese sueldo")]
        [Display(Name = "Sueldo")]
        public double sueldo { get; set; }
    }
}

app_ventas_ds504_cf/Controllers/HomeController.cs
using app_ventas_ds504_cf.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace app_ventas_ds504_cf.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

app_ventas_ds504_cf/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using web_ventas_ds504_cf.Data;
using web_ventas_ds504_cf.Models;

namespace web_ventas_ds504_cf.Controllers
{
    public class MarcaController : Controller
    {
        private readonly ApplicationDbContext _context;
        public MarcaController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Marca> ListarMarca = _context.Marca;
            return View(ListarMarca);
        }
    }
}

app_ventas_ds504_cf/Controllers/PersonalController.cs
using Microsoft.AspNetCore.Mvc;
using ProyectoDS504_cf.Models;
using web_ventas_ds504_cf.Data;

namespace web_ventas_ds504_cf.Controllers
{
    public class PersonalController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PersonalController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Personal> listarPersonal = _context.Personal;
            return View(listarPersonal);
        }
    }
}

app_ventas_ds504_cf/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

app_ventas_ds504_cf/Views/Marca/Index.cshtml
@model IEnumerable<web_ventas_ds504_cf.Models.Marca>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Listado de Marcas</h1>
<hr />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <a class="btn btn-success" asp-controller="Marca"
               asp-action="Create"><i class="fa fa-plus-circle"></i>Agregar Marca</a>
        </div>
    </div>

    <br />

    <div class="row">
        @if (Model.Count() > 0)
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>@Html.DisplayNameFor(marca => marca.codigo_marca)</td>
                        <td>@Html.DisplayNameFor(marca => marca.marca)</td>
                        <td>Acciones</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var reg in Model)
                    {
                        <tr>
                            <td>@reg.codigo_marca</td>
                            <td>@reg.marca</td>
                            <td>
                                <a asp-controller="Marca" asp-action="Edit"
                                   asp-route-id="@reg.codigo_marca"
                                   class="btn btn-outline-warning btn-sm"><i class="fas fa-edit"></i> Editar</a>

                                <a asp-controller="Marca" asp-action="Delete"
                                   asp-route-id="@reg.codigo_marca"
                                   class="btn btn-outline-danger btn-sm"><i class="fas fa-trash-alt"></i> Borrar</a>
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
            <h5>Elaborado por: SACA MACHACA CESAR</h5>
        }
        else
        {
            <p>No existen registros</p>
        }
    </div>
</div>

app_ventas_ds504_cf/Views/Personal/Index.cshtml
@model IEnumerable<ProyectoDS504_cf.Models.Personal>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Listado del Personal</h1>
<hr />

<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <a class="btn btn-success" asp-controller="Personal" asp-action="Create">
                <i class="fa fa-plus-circle"></i>
                Agregar Personal
            </a>
        </div>
    </div>
</div>

<br />

<div class="row">
    @if (Model.Count() > 0)
    {

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(per => per.dni)</th>
                    <th>@Html.DisplayNameFor(per => per.ap_paterno)</th>
                    <th>@Html.DisplayNameFor(per => per.ap_materno)</th>
                    <th>@Html.DisplayNameFor(per => per.nombre)</th>
                    <th>@Html.DisplayNameFor(per => per.fecha_nacimiento)</th>
                    <th>@Html.DisplayNameFor(per => per.genero)</th>
                    <th>@Html.DisplayNameFor(per => per.sueldo)</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var reg in Model)
                {
                    <tr>
                        <td>@reg.dni</td>
                        <td>@reg.ap_paterno</td>
                        <td>@reg.ap_materno</td>
                        <td>@reg.nombre</td>
                        <td>@reg.fecha_nacimiento</td>
                        <td>@reg.genero</td>
                        <td>@reg.sueldo</td>
                        <td>
                            <a asp-controller="Personal" asp-action="Edit"
                               asp-route-id="@reg.dni"
                               class="btn btn-outline-warning btn-sm"><i class="fas fa-edit"></i>Editar</a>

                            <a asp-controller="Personal" asp-action="Delete"
                               asp-route-id="@reg.dni"
                               class="btn btn-outline-danger btn-sm"><i class="fas fa-trash-alt"></i>Borrar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h5>Elaborado por: SACA MACHACA CESAR</h5>
    }
    else
    {
        <p>No existen registros</p>
    }
</div>

app_ventas_ds504_cf/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - app_ventas_ds504_cf</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/app_ventas_ds504_cf.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">app_ventas_ds504_cf</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personal" asp-action="Index">Personal</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marca</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - app_ventas_ds504_cf - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>